In [1]:
import os
import pandas as pd
import numpy as np

np.random.seed(42)

In [2]:
__author__ = ['Aleksandar Anžel']
__copyright__ = ''
__credits__ = ['Aleksandar Anžel', 'Georges Hattab']
__license__ = 'GNU General Public License v3.0'
__version__ = '1.0.0'
__maintainer__ = 'Aleksandar Anžel'
__email__ = 'AnzelA@rki.de'
__status__ = 'Stable'

In [3]:
path_wine_root = os.path.join('..', '..', 'data', 'Case_Study_Wine')
path_wine_original = os.path.join(path_wine_root, 'winequality-red.csv')
path_wine_result = os.path.join(path_wine_root, 'wine_sampled.csv')
df_wine_original = pd.read_csv(path_wine_original, sep=';')
df_wine_original

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
df_wine_original.dropna(inplace=True)
df_wine_original

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [5]:
df_wine_sampled = df_wine_original.groupby('quality').apply(
    lambda x: x.sample(frac=0.0125)).droplevel(0)
df_wine_sampled

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
18,7.4,0.590,0.08,4.4,0.086,6.0,29.0,0.99740,3.38,0.50,9.0
185,8.9,0.310,0.57,2.0,0.111,26.0,85.0,0.99710,3.26,0.53,9.7
373,7.4,0.550,0.22,2.2,0.106,12.0,72.0,0.99590,3.05,0.63,9.2
705,8.4,1.035,0.15,6.0,0.073,11.0,54.0,0.99900,3.37,0.49,9.9
1373,7.7,0.750,0.27,3.8,0.110,34.0,89.0,0.99664,3.24,0.45,9.3
793,7.7,0.600,0.00,2.6,0.055,7.0,13.0,0.99639,3.38,0.56,10.8
1391,8.0,0.640,0.22,2.4,0.094,5.0,33.0,0.99612,3.37,0.58,11.0
120,7.3,1.070,0.09,1.7,0.178,10.0,89.0,0.99620,3.30,0.57,9.0
846,6.4,0.640,0.21,1.8,0.081,14.0,31.0,0.99689,3.59,0.66,9.8
796,8.7,0.460,0.31,2.5,0.126,24.0,64.0,0.99746,3.10,0.74,9.6
493,8.7,0.690,0.31,3.0,0.086,23.0,81.0,1.00020,3.48,0.74,11.6
70,7.7,0.630,0.08,1.9,0.076,15.0,27.0,0.99670,3.32,0.54,9.5
762,8.8,0.700,0.00,1.7,0.069,8.0,19.0,0.99701,3.31,0.53,10.0
829,5.9,0.610,0.08,2.1,0.071,16.0,24.0,0.99376,3.56,0.77,11.1
1174,7.6,0.360,0.31,1.7,0.079,26.0,65.0,0.99716,3.46,0.62,9.5
1123,10.7,0.400,0.37,1.9,0.081,17.0,29.0,0.99674,3.12,0.65,11.2
1422,7.0,0.540,0.00,2.1,0.079,39.0,55.0,0.99560,3.39,0.84,11.4
867,6.9,0.510,0.23,2.0,0.072,13.0,22.0,0.99438,3.40,0.84,11.2
320,9.8,0.660,0.39,3.2,0.083,21.0,59.0,0.99890,3.37,0.71,11.5
874,10.4,0.380,0.46,2.1,0.104,6.0,10.0,0.99664,3.12,0.65,11.8

In [6]:
#df_wine_sampled = df_wine_sampled.drop('quality', axis=1)
df_wine_sampled['Wine'] = ['Wine_' + str(i)
                           for i in range(df_wine_sampled.shape[0])]
df_wine_sampled

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Wine
18,7.4,0.590,0.08,4.4,0.086,6.0,29.0,0.99740,3.38,0.50,9.0,Wine_0
185,8.9,0.310,0.57,2.0,0.111,26.0,85.0,0.99710,3.26,0.53,9.7,Wine_1
373,7.4,0.550,0.22,2.2,0.106,12.0,72.0,0.99590,3.05,0.63,9.2,Wine_2
705,8.4,1.035,0.15,6.0,0.073,11.0,54.0,0.99900,3.37,0.49,9.9,Wine_3
1373,7.7,0.750,0.27,3.8,0.110,34.0,89.0,0.99664,3.24,0.45,9.3,Wine_4
793,7.7,0.600,0.00,2.6,0.055,7.0,13.0,0.99639,3.38,0.56,10.8,Wine_5
1391,8.0,0.640,0.22,2.4,0.094,5.0,33.0,0.99612,3.37,0.58,11.0,Wine_6
120,7.3,1.070,0.09,1.7,0.178,10.0,89.0,0.99620,3.30,0.57,9.0,Wine_7
846,6.4,0.640,0.21,1.8,0.081,14.0,31.0,0.99689,3.59,0.66,9.8,Wine_8
796,8.7,0.460,0.31,2.5,0.126,24.0,64.0,0.99746,3.10,0.74,9.6,Wine_9
493,8.7,0.690,0.31,3.0,0.086,23.0,81.0,1.00020,3.48,0.74,11.6,Wine_10
70,7.7,0.630,0.08,1.9,0.076,15.0,27.0,0.99670,3.32,0.54,9.5,Wine_11
762,8.8,0.700,0.00,1.7,0.069,8.0,19.0,0.99701,3.31,0.53,10.0,Wine_12
829,5.9,0.610,0.08,2.1,0.071,16.0,24.0,0.99376,3.56,0.77,11.1,Wine_13
1174,7.6,0.360,0.31,1.7,0.079,26.0,65.0,0.99716,3.46,0.62,9.5,Wine_14
1123,10.7,0.400,0.37,1.9,0.081,17.0,29.0,0.99674,3.12,0.65,11.2,Wine_15
1422,7.0,0.540,0.00,2.1,0.079,39.0,55.0,0.99560,3.39,0.84,11.4,Wine_16
867,6.9,0.510,0.23,2.0,0.072,13.0,22.0,0.99438,3.40,0.84,11.2,Wine_17
320,9.8,0.660,0.39,3.2,0.083,21.0,59.0,0.99890,3.37,0.71,11.5,Wine_18
874,10.4,0.380,0.46,2.1,0.104,6.0,10.0,0.99664,3.12,0.65,11.8,Wine_19

In [7]:
df_wine_sampled_pivoted = df_wine_sampled.pivot_table(columns='Wine')
df_wine_sampled_pivoted

Wine,Wine_0,Wine_1,Wine_10,Wine_11,Wine_12,Wine_13,Wine_14,Wine_15,Wine_16,Wine_17,Wine_18,Wine_19,Wine_2,Wine_3,Wine_4,Wine_5,Wine_6,Wine_7,Wine_8,Wine_9
alcohol,9.0000,9.7000,11.6000,9.5000,10.00000,11.10000,9.50000,11.20000,11.4000,11.20000,11.5000,11.80000,9.2000,9.900,9.30000,10.80000,11.00000,9.0000,9.80000,9.60000
chlorides,0.0860,0.1110,0.0860,0.0760,0.06900,0.07100,0.07900,0.08100,0.0790,0.07200,0.0830,0.10400,0.1060,0.073,0.11000,0.05500,0.09400,0.1780,0.08100,0.12600
citric acid,0.0800,0.5700,0.3100,0.0800,0.00000,0.08000,0.31000,0.37000,0.0000,0.23000,0.3900,0.46000,0.2200,0.150,0.27000,0.00000,0.22000,0.0900,0.21000,0.31000
density,0.9974,0.9971,1.0002,0.9967,0.99701,0.99376,0.99716,0.99674,0.9956,0.99438,0.9989,0.99664,0.9959,0.999,0.99664,0.99639,0.99612,0.9962,0.99689,0.99746
fixed acidity,7.4000,8.9000,8.7000,7.7000,8.80000,5.90000,7.60000,10.70000,7.0000,6.90000,9.8000,10.40000,7.4000,8.400,7.70000,7.70000,8.00000,7.3000,6.40000,8.70000
free sulfur dioxide,6.0000,26.0000,23.0000,15.0000,8.00000,16.00000,26.00000,17.00000,39.0000,13.00000,21.0000,6.00000,12.0000,11.000,34.00000,7.00000,5.00000,10.0000,14.00000,24.00000
pH,3.3800,3.2600,3.4800,3.3200,3.31000,3.56000,3.46000,3.12000,3.3900,3.40000,3.3700,3.12000,3.0500,3.370,3.24000,3.38000,3.37000,3.3000,3.59000,3.10000
residual sugar,4.4000,2.0000,3.0000,1.9000,1.70000,2.10000,1.70000,1.90000,2.1000,2.00000,3.2000,2.10000,2.2000,6.000,3.80000,2.60000,2.40000,1.7000,1.80000,2.50000
sulphates,0.5000,0.5300,0.7400,0.5400,0.53000,0.77000,0.62000,0.65000,0.8400,0.84000,0.7100,0.65000,0.6300,0.490,0.45000,0.56000,0.58000,0.5700,0.66000,0.74000
total sulfur dioxide,29.0000,85.0000,81.0000,27.0000,19.00000,24.00000,65.00000,29.00000,55.0000,22.00000,59.0000,10.00000,72.0000,54.000,89.00000,13.00000,33.00000,89.0000,31.00000,64.00000
volatile acidity,0.5900,0.3100,0.6900,0.6300,0.70000,0.61000,0.36000,0.40000,0.5400,0.51000,0.6600,0.38000,0.5500,1.035,0.75000,0.60000,0.64000,1.0700,0.64000,0.46000

In [8]:
series_median = df_wine_sampled[df_wine_sampled.drop('Wine', axis=1).columns.to_list()].median()
series_median

fixed acidity            7.70000
volatile acidity         0.60500
citric acid              0.22000
residual sugar           2.10000
chlorides                0.08200
free sulfur dioxide     14.50000
total sulfur dioxide    43.50000
density                  0.99672
pH                       3.37000
sulphates                0.62500
alcohol                  9.95000
dtype: float64

In [9]:
df_wine_sampled_pivoted['Median'] = series_median
df_wine_sampled_pivoted

Wine,Wine_0,Wine_1,Wine_10,Wine_11,Wine_12,Wine_13,Wine_14,Wine_15,Wine_16,Wine_17,...,Wine_19,Wine_2,Wine_3,Wine_4,Wine_5,Wine_6,Wine_7,Wine_8,Wine_9,Median
alcohol,9.0000,9.7000,11.6000,9.5000,10.00000,11.10000,9.50000,11.20000,11.4000,11.20000,...,11.80000,9.2000,9.900,9.30000,10.80000,11.00000,9.0000,9.80000,9.60000,9.95000
chlorides,0.0860,0.1110,0.0860,0.0760,0.06900,0.07100,0.07900,0.08100,0.0790,0.07200,...,0.10400,0.1060,0.073,0.11000,0.05500,0.09400,0.1780,0.08100,0.12600,0.08200
citric acid,0.0800,0.5700,0.3100,0.0800,0.00000,0.08000,0.31000,0.37000,0.0000,0.23000,...,0.46000,0.2200,0.150,0.27000,0.00000,0.22000,0.0900,0.21000,0.31000,0.22000
density,0.9974,0.9971,1.0002,0.9967,0.99701,0.99376,0.99716,0.99674,0.9956,0.99438,...,0.99664,0.9959,0.999,0.99664,0.99639,0.99612,0.9962,0.99689,0.99746,0.99672
fixed acidity,7.4000,8.9000,8.7000,7.7000,8.80000,5.90000,7.60000,10.70000,7.0000,6.90000,...,10.40000,7.4000,8.400,7.70000,7.70000,8.00000,7.3000,6.40000,8.70000,7.70000
free sulfur dioxide,6.0000,26.0000,23.0000,15.0000,8.00000,16.00000,26.00000,17.00000,39.0000,13.00000,...,6.00000,12.0000,11.000,34.00000,7.00000,5.00000,10.0000,14.00000,24.00000,14.50000
pH,3.3800,3.2600,3.4800,3.3200,3.31000,3.56000,3.46000,3.12000,3.3900,3.40000,...,3.12000,3.0500,3.370,3.24000,3.38000,3.37000,3.3000,3.59000,3.10000,3.37000
residual sugar,4.4000,2.0000,3.0000,1.9000,1.70000,2.10000,1.70000,1.90000,2.1000,2.00000,...,2.10000,2.2000,6.000,3.80000,2.60000,2.40000,1.7000,1.80000,2.50000,2.10000
sulphates,0.5000,0.5300,0.7400,0.5400,0.53000,0.77000,0.62000,0.65000,0.8400,0.84000,...,0.65000,0.6300,0.490,0.45000,0.56000,0.58000,0.5700,0.66000,0.74000,0.62500
total sulfur dioxide,29.0000,85.0000,81.0000,27.0000,19.00000,24.00000,65.00000,29.00000,55.0000,22.00000,...,10.00000,72.0000,54.000,89.00000,13.00000,33.00000,89.0000,31.00000,64.00000,43.50000
volatile acidity,0.5900,0.3100,0.6900,0.6300,0.70000,0.61000,0.36000,0.40000,0.5400,0.51000,...,0.38000,0.5500,1.035,0.75000,0.60000,0.64000,1.0700,0.64000,0.46000,0.60500

In [10]:
df_wine_sampled_pivoted.to_csv(path_wine_result, index=False)